### ISSUE TITLE
WDT and RTC Not working together

### ISSUE THREAD

**Issue by mattb1969** [javos65/WDTZero#6]
Hi,
I noticed a previous comment that was closed without an actual resolution, I think it was misunderstood as reading the post suggests a similar set of issues that I am currently experiencing.
(https://github.com/javos65/WDTZero/issues/2)

Using MKRWAN 1310 board

If I this WDT timer running, it works fine. When set to 16 seconds, it reset the processor at the right time.

If I have a RTC timer running, it happily triggers every 30 seconds as configured. This has been modified to use the OSCULP32K clock as per another post to reduce power (https://forum.arduino.cc/index.php?topic=553612.0).
(https://github.com/arduino-libraries/RTCZero)

If I have a RTC and a WDT both configured within the application, neither appear to work correctly.
- RTC becomes unreliable - triggering anytime between the configured 30 seconds and over a minute
- WDT stops working at all.

I have looked at the configuration for both, they are using the same clock (GCLK_GENCTRL_SRC_OSCULP32K), they both have the same basic setup
GCLK->GENCTRL.reg = (GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_OSCULP32K | GCLK_GENCTRL_ID(2) | GCLK_GENCTRL_DIVSEL );

Yet the system is not working. I am not a clock expert, so I am a little uncertain as to how to resolve the issue. I am not sure it is even an issue with this library,

**Comment by javos65** [comment]
Hi,m sorry for my late reply.
I expect there is a conflict with clock resources or clock settings among RTC and WDT.
Need to figure this out when I have the time :)

**Comment by DamonLane** [comment]
I don't want to "me too" or hijack, but I'm having an issue that could be related and therefore may help figure out what's happening. In my case, documented by someone else here: https://forum.arduino.cc/index.php?topic=619945.0, it's ArduinoLowPower and WDTZero that don't work together. I'm trying to use several minutes of sleep and the 16M softcycle, but the device resets very quickly, defintely within a minute, but I can't tell how quickly from the remote data.

**Comment by andreacosti** [comment]
I'm very interested in the solution of this bug too.

**Comment by mattb1969** [comment]
Check out this link. I’ve taken what is here and built it further with low power in mind.I’ve not configured long sleep cycles, the example is only a few seconds, but the framework is there for longer, but you’ll need to get to grips with various register settings for a longer time period and make use of the Early warning feature.

https://github.com/mattb1969/InterruptswithRTCandWDT
